# Generated by Django 3.2.9 on 2021-11-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='role',
        ),
    ]
