# Generated by Django 3.2.9 on 2021-11-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0006_auto_20211113_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='equepmentmaster',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equepmentmaster',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='equepmentmaster',
            name='status',
            field=models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'deleted')]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'deleted')]),
        ),
        migrations.AlterField(
            model_name='region',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, 'inactive'), (1, 'active'), (2, 'deleted')]),
        ),
        migrations.AlterField(
            model_name='whwarehouse',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='whwarehouse',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
