# Generated by Django 3.2.9 on 2021-11-16 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0007_auto_20211114_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouseid', models.AutoField(primary_key=True, serialize=False)),
                ('warehousename', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modify', models.DateTimeField(auto_now=True)),
                ('cityid', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='testapp1.city')),
            ],
        ),
        migrations.DeleteModel(
            name='whWarehouse',
        ),
    ]
