# Generated by Django 3.2.9 on 2021-11-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0008_auto_20211116_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='countryid',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cityid',
        ),
        migrations.RemoveField(
            model_name='equepmentmaster',
            name='cityid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='cityid',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='cityid',
        ),
        migrations.AddField(
            model_name='client',
            name='clientcity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equepmentmaster',
            name='equepmentcity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='projectcity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='werehousecity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
