# Generated by Django 3.2.9 on 2021-11-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0009_auto_20211116_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
