# Generated by Django 3.2.9 on 2021-11-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0011_auto_20211116_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='equepmentmaster',
            name='equepmentname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Equepmentdetails',
        ),
    ]
